version: '3'

services:
  web:
    build: .
    command: ["./init.sh"]
    environment:
      - "SECRET_KEY=#9n5v_uwn+880+53w_avj&fp!ul=wf^jlls7t+v5f^z4553i98"
      - "MODE=docker"
      - "REFRESH_INTERVAL=10"
    volumes:
      - .:/code
    privileged: true
    ports:
      - "8000:8000"
    restart: always