version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./data:/usr/share/nginx/html
    ports:
      - "9000:80"
  web:
    build: .
    command: ["./init.sh"]
    environment:
      - "SECRET_KEY=#9n5v_uwn+880+53w_avj&fp!ul=wf^jlls7t+v5f^z4553i98"
      - "MODE=remote"
      - "REFRESH_INTERVAL=10"
    volumes:
      - .:/code
    privileged: true
    ports:
      - "7000:8000"
    restart: always